export const servicoData = [
  {
    id: "1",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    desigSistema: "Sistema de Recargas",
    desigEcra: "Recargas Principais",
    desigTeclaSeleccao: "1",
    empresaId: "empresa-001",
  },
  {
    id: "2",
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
    desigSistema: "Sistema de Pagamentos",
    desigEcra: "Pagamentos Utilitários",
    desigTeclaSeleccao: "2",
    empresaId: "empresa-001",
  },
  {
    id: "3",
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17"),
    desigSistema: "Sistema de Consultas",
    desigEcra: "Consultas Saldo",
    desigTeclaSeleccao: "3",
    empresaId: "empresa-001",
  },
  {
    id: "4",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
    desigSistema: "Sistema de Transferências",
    desigEcra: "Transferências Internas",
    desigTeclaSeleccao: "4",
    empresaId: "empresa-001",
  },
  {
    id: "5",
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19"),
    desigSistema: "Sistema de Cartões",
    desigEcra: "Gestão de Cartões",
    desigTeclaSeleccao: "5",
    empresaId: "empresa-002",
  },
  {
    id: "6",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    desigSistema: "Sistema de Faturas",
    desigEcra: "Pagamento Faturas",
    desigTeclaSeleccao: "6",
    empresaId: "empresa-002",
  },
  {
    id: "7",
    createdAt: new Date("2024-01-21"),
    updatedAt: new Date("2024-01-21"),
    desigSistema: "Sistema de Donativos",
    desigEcra: "Doações Caridade",
    desigTeclaSeleccao: "7",
    empresaId: "empresa-002",
  },
  {
    id: "8",
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
    desigSistema: "Sistema de Jogos",
    desigEcra: "Aposta Desportiva",
    desigTeclaSeleccao: "8",
    empresaId: "empresa-003",
  },
  {
    id: "9",
    createdAt: new Date("2024-01-23"),
    updatedAt: new Date("2024-01-23"),
    desigSistema: "Sistema de Transportes",
    desigEcra: "Bilhetes Autocarro",
    desigTeclaSeleccao: "9",
    empresaId: "empresa-003",
  },
  {
    id: "10",
    createdAt: new Date("2024-01-24"),
    updatedAt: new Date("2024-01-24"),
    desigSistema: "Sistema de Entretenimento",
    desigEcra: "Streaming Serviços",
    desigTeclaSeleccao: "0",
    empresaId: "empresa-003",
  },
  {
    id: "11",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
    desigSistema: "Sistema de Seguros",
    desigEcra: "Pagamento Prémios",
    desigTeclaSeleccao: "A",
    empresaId: "empresa-004",
  },
  {
    id: "12",
    createdAt: new Date("2024-01-26"),
    updatedAt: new Date("2024-01-26"),
    desigSistema: "Sistema de Saúde",
    desigEcra: "Marcação Consultas",
    desigTeclaSeleccao: "B",
    empresaId: "empresa-004",
  },
  {
    id: "13",
    createdAt: new Date("2024-01-27"),
    updatedAt: new Date("2024-01-27"),
    desigSistema: "Sistema de Educação",
    desigEcra: "Propinas Escolares",
    desigTeclaSeleccao: "C",
    empresaId: "empresa-004",
  },
  {
    id: "14",
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-01-28"),
    desigSistema: "Sistema de Turismo",
    desigEcra: "Reservas Hotel",
    desigTeclaSeleccao: "D",
    empresaId: "empresa-005",
  },
  {
    id: "15",
    createdAt: new Date("2024-01-29"),
    updatedAt: new Date("2024-01-29"),
    desigSistema: "Sistema de Restauração",
    desigEcra: "Pedido Delivery",
    desigTeclaSeleccao: "E",
    empresaId: "empresa-005",
  },
  {
    id: "16",
    createdAt: new Date("2024-01-30"),
    updatedAt: new Date("2024-01-30"),
    desigSistema: "Sistema de Combustível",
    desigEcra: "Pagamento Bomba",
    desigTeclaSeleccao: "F",
    empresaId: "empresa-005",
  },
  {
    id: "17",
    createdAt: new Date("2024-01-31"),
    updatedAt: new Date("2024-01-31"),
    desigSistema: "Sistema de Parques",
    desigEcra: "Estacionamento",
    desigTeclaSeleccao: "G",
    empresaId: "empresa-006",
  },
  {
    id: "18",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
    desigSistema: "Sistema de Taxi",
    desigEcra: "Chamada Taxi",
    desigTeclaSeleccao: "H",
    empresaId: "empresa-006",
  },
];
