import type { Entidade } from "@/types";

export const entidade: Entidade = {
  id: "E1",
  utilizadorId: "U1",
  cae: "12345",
  localidade: "Localidade",
  morada: "Morada",
  nome: "Backbone, Lda",
  numero_pessoa_colectiva: "1234567890",
  sigla: "Backbone",
  responsavel: "Ruben Silva",
  telefone: "923456789",
  email: "ruben@backbone.com",
  numero_entidade: "1234567890",
  desig_ecra: "BACKBONE",
  desig_tecla_seleccao: "Backbone",
  servicos: [
    {
      id: "S1",
      empresaId: "E1",
      desig_sistema: "Mimo SMS",
      desig_ecra: "Mimo SMS",
      desig_tecla_seleccao_1: "Mimo SMS",
      desig_tecla_seleccao_2: "Serviço Bulk SMS",
      produtos: [
        {
          id: "P1",
          servicoId: "S1",
          type: "pagamento",
          desig_ecra: "Mimo Pagamentos",
          desig_tecla_seleccao: "Carregamento Livre",
          pagamento: {
            id: "PG1",
            produtoId: "P1",
            desig_referencia: "Utilizador",
            tamanho_referencia: 9,
            texto_ecra_referencia: "Insira o utilizador (número de telemóvel)",
            isNew: true,
            montante_minimo: 1000.0,
            montante_maximo: 500000.0,
          },
        },
        {
          id: "P2",
          servicoId: "S1",
          type: "carregamentos",
          desig_ecra: "Mimo Carregamentos",
          desig_tecla_seleccao: "Carregamentos",
          carregamento: {
            id: "CG1",
            produtoId: "P2",
            desig_referencia: "Utilizador",
            tamanho_referencia: 9,
            texto_ecra_referencia: "Insira o utilizador (número de telemóvel)",
            montante_tipo: "montante_pre_definido",
            montante_livre: false,
            montante_minimo: 10,
            montante_maximo: 10,
            montante_pre_definido: true,
            montantes: [
              {
                id: "MG1",
                carregamentoId: "CG1",
                montante: 1260.0,
                descricao: "100 SMS",
              },
              {
                id: "MG2",
                carregamentoId: "CG1",
                montante: 6213.0,
                descricao: "500 SMS",
              },
              {
                id: "MG2",
                carregamentoId: "CG1",
                montante: 12426.0,
                descricao: "1000 SMS",
              },
              {
                id: "MG2",
                carregamentoId: "CG1",
                montante: 24852.0,
                descricao: "2000 SMS",
              },
              {
                id: "MG2",
                carregamentoId: "CG1",
                montante: 37278.0,
                descricao: "3000 SMS",
              },
              {
                id: "MG2",
                carregamentoId: "CG1",
                montante: 49704.0,
                descricao: "4000 SMS",
              },
              {
                id: "MG2",
                carregamentoId: "CG1",
                montante: 62130.0,
                descricao: "5000 SMS",
              },
            ],
          },
        },
        {
          id: "P3",
          servicoId: "S1",
          type: "recargas",
          desig_ecra: "Mimo Recargas",
          desig_tecla_seleccao: "Recargas",
          recargas: {
            id: "RG1",
            produtoId: "P3",
            recargas: [
              {
                id: "RGS1",
                recargasId: "RG1",
                desig_unidade: "100 SMS",
                desig_montante: 1260.0,
              },
              {
                id: "RGS2",
                recargasId: "RG1",
                desig_unidade: "500 SMS",
                desig_montante: 6213.0,
              },
              {
                id: "RGS3",
                recargasId: "RG1",
                desig_unidade: "1000 SMS",
                desig_montante: 12426.0,
              },
              {
                id: "RGS4",
                recargasId: "RG1",
                desig_unidade: "2000 SMS",
                desig_montante: 24852.0,
              },
              {
                id: "RGS5",
                recargasId: "RG1",
                desig_unidade: "3000 SMS",
                desig_montante: 37278.0,
              },
              {
                id: "RGS6",
                recargasId: "RG1",
                desig_unidade: "4000 SMS",
                desig_montante: 49704.0,
              },
              {
                id: "RGS7",
                recargasId: "RG1",
                desig_unidade: "5000 SMS",
                desig_montante: 62130.0,
              },
            ],
          },
        },
      ],
    },
    {
      id: "S2",
      empresaId: "E1",
      desig_sistema: "Mimo WhatsApp",
      desig_ecra: "Mimo WhatsApp",
      desig_tecla_seleccao_1: "Mimo WhatsApp",
      desig_tecla_seleccao_2: "Serviço WhatsApp Business",
      produtos: [],
    },
  ],
};
