import { Geist, Geist_Mono } from "next/font/google";

import { RootWrapper, PageWrapper } from "@/components/wrappers";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { AuthProvider, StylesProvider } from "@/components/providers";
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";

import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en" {...mantineHtmlProps}>
        <head>
          <ColorSchemeScript />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <StylesProvider>
            <RootWrapper>
              <Header />
              <PageWrapper>{children}</PageWrapper>
              <Footer />
            </RootWrapper>
          </StylesProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
